CREATE TABLE llx_operationorder (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  date_creation datetime DEFAULT NULL,
  tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ref varchar(255) DEFAULT NULL,
  ref_client varchar(255) DEFAULT NULL,
  fk_soc integer NOT NULL DEFAULT 0,
  fk_contrat integer DEFAULT 0,
  date_valid datetime DEFAULT NULL,
  date_cloture datetime DEFAULT NULL,
  date_operation_order datetime DEFAULT NULL,
  note_public varchar(255) DEFAULT NULL,
  note_private varchar(255) DEFAULT NULL,
  fk_user_creat integer NOT NULL DEFAULT 0,
  fk_user_modif integer DEFAULT 0,
  fk_user_valid integer DEFAULT 0,
  fk_user_cloture integer DEFAULT 0,
  import_key varchar(255) DEFAULT NULL,
  model_pdf varchar(255) DEFAULT NULL,
  status int(8) DEFAULT NULL,
  last_main_doc varchar(255) DEFAULT NULL,
  entity integer NOT NULL DEFAULT 0,
  time_planned_t integer NOT NULL DEFAULT 0,
  time_planned_f integer DEFAULT 0,
  planned_date datetime DEFAULT NULL,
  total_ht_reimbursement double NOT NULL DEFAULT 0,
  total_ht_part double NOT NULL DEFAULT 0,
  total_ht_service double NOT NULL DEFAULT 0,
  total_ht_external double NOT NULL DEFAULT 0,
  total_ht_mo double NOT NULL DEFAULT 0,
  total_ht double NOT NULL DEFAULT 0,
  orcheck integer NOT NULL DEFAULT 0,
  fk_user_meca integer DEFAULT 0,
  fk_vehicule integer NOT NULL DEFAULT 0,
  fk_conducteur integer DEFAULT 0,
  km_on_creation integer NOT NULL DEFAULT 0,
  categories varchar(255) DEFAULT NULL
) ENGINE=innodb;
