CREATE TABLE llx_workshop_vehicule (
									   rowid integer AUTO_INCREMENT PRIMARY KEY,
									   date_creation datetime DEFAULT NULL,
									   tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
									   vin varchar(50) NOT NULL DEFAULT '',
									   entity integer NOT NULL DEFAULT 0,
									   status integer NOT NULL DEFAULT 0,
									   fk_vehicule_type integer NOT NULL DEFAULT 0,
									   fk_vehicule_mark integer NOT NULL DEFAULT 0,
									   modele varchar(255) DEFAULT NULL,
									   immatriculation varchar(20) NOT NULL DEFAULT '',
									   date_immat datetime DEFAULT NULL,
									   fk_soc integer DEFAULT 0,
									   date_customer_exploit datetime DEFAULT NULL,
									   km double DEFAULT 0,
									   km_date datetime DEFAULT NULL,
									   fk_contract_type integer DEFAULT NULL,
									   date_end_contract datetime DEFAULT NULL,
									   atelier integer DEFAULT NULL,
									   carrosserie longtext DEFAULT NULL,
									   dfol integer NOT NULL DEFAULT 0,
									   nb_pneu integer DEFAULT 0,
									   dim_pneu varchar(255) DEFAULT NULL,
									   essieu varchar(255) DEFAULT NULL,
									   type_custom integer DEFAULT NULL,
									   coutm double DEFAULT NULL,
									   date_fin_fin datetime DEFAULT NULL,
									   type_fin varchar(255) DEFAULT NULL,
									   com_custom longtext DEFAULT NULL,
									   date_fin_loc datetime DEFAULT NULL,
									   exit_data integer DEFAULT 0,
									   age_veh integer DEFAULT 0,
									   import_key varchar(14) DEFAULT NULL
)ENGINE=innodb;
