CREATE TABLE llx_workshop_operationorder (
  rowid                  integer AUTO_INCREMENT PRIMARY KEY,
  date_creation          datetime         DEFAULT NULL,
  tms                    timestamp        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ref                    varchar(255)     DEFAULT NULL,
  ref_client             varchar(255)     DEFAULT NULL,
  entity                 integer NOT NULL DEFAULT 1,
  fk_soc                 integer NOT NULL DEFAULT 0,
  fk_vehicule            integer NOT NULL DEFAULT 0,
  fk_conducteur          integer          DEFAULT NULL,
  date_valid             datetime         DEFAULT NULL,
  date_start             datetime         DEFAULT NULL,
  date_end               datetime         DEFAULT NULL,
  date_planned           datetime         DEFAULT NULL,
  km                     double           DEFAULT 0,
  note_public            longtext         DEFAULT NULL,
  note_private           longtext         DEFAULT NULL,
  fk_user_creat          integer NOT NULL DEFAULT 0,
  fk_user_modif          integer          DEFAULT NULL,
  fk_user_valid          integer          DEFAULT NULL,
  fk_user_assign         integer          DEFAULT NULL,
  model_pdf              varchar(255)     DEFAULT NULL,
  last_main_doc          varchar(255)     DEFAULT NULL,
  total_ht               double  NOT NULL DEFAULT 0,
  total_ht_part          double  NOT NULL DEFAULT 0,
  total_ht_mo            double  NOT NULL DEFAULT 0,
  total_ht_service       double  NOT NULL DEFAULT 0,
  total_ht_external      double  NOT NULL DEFAULT 0,
  total_ht_refund        double  NOT NULL DEFAULT 0,
  import_key             varchar(255)     DEFAULT NULL,
  status                 integer NOT NULL DEFAULT 0
) ENGINE=innodb;
