CREATE TABLE llx_workshop_vehicule (
	-- BEGIN MODULEBUILDER FIELDS
	rowid integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
	vin varchar(50) NOT NULL,
	entity integer NOT NULL DEFAULT 1,
	status integer NOT NULL DEFAULT 0,
	fk_vehicule_type integer NOT NULL DEFAULT 0,
	fk_vehicule_mark integer NOT NULL DEFAULT 0,
	modele varchar(255),
	immatriculation varchar(20) NOT NULL DEFAULT '',
	date_immat date,
	fk_soc integer,
	date_customer_exploit date,
	km double NOT NULL DEFAULT 0,
	km_date date,
	fk_contract_type integer,
	date_end_contract date,
	atelier integer,
	carrosserie longtext,
	dfol integer NOT NULL DEFAULT 0,
	nb_pneu integer,
	dim_pneu varchar(255),
	essieu varchar(255),
	type_custom integer,
	coutm double,
	date_fin_fin date,
	type_fin varchar(255),
	com_custom longtext,
	date_fin_loc date,
	exit_data integer,
	age_veh integer,
	note_public text,
	note_private text,
	import_key varchar(14),
	date_creation datetime,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	-- END MODULEBUILDER FIELDS
)ENGINE=innodb;
