ALTER TABLE llx_workshop_operationorder_status_target ADD UNIQUE INDEX uk_workshop_or_status_target (fk_workshop_operationorderstatus, fk_workshop_operationorderstatus_target);

ALTER TABLE llx_workshop_operationorder_status_target ADD INDEX idx_workshop_or_status_target_src (fk_workshop_operationorderstatus);
ALTER TABLE llx_workshop_operationorder_status_target ADD INDEX idx_workshop_or_status_target_dst (fk_workshop_operationorderstatus_target);

ALTER TABLE llx_workshop_operationorder_status_target ADD CONSTRAINT fk_workshop_or_status_target_src FOREIGN KEY (fk_workshop_operationorderstatus) REFERENCES llx_workshop_operationorder_status (rowid);
ALTER TABLE llx_workshop_operationorder_status_target ADD CONSTRAINT fk_workshop_or_status_target_dst FOREIGN KEY (fk_workshop_operationorderstatus_target) REFERENCES llx_workshop_operationorder_status (rowid);
