CREATE TABLE llx_workshop_planning (
  rowid                  integer AUTO_INCREMENT PRIMARY KEY,
  date_creation          datetime         DEFAULT NULL,
  tms                    timestamp        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_object              integer NOT NULL DEFAULT 0,
  object_type            varchar(50)  NOT NULL DEFAULT 'workshop',
  entity                 integer NOT NULL DEFAULT 1,
  active                 tinyint NOT NULL DEFAULT 1,
  lundi_heuredam         varchar(5)       DEFAULT NULL,
  lundi_heurefam         varchar(5)       DEFAULT NULL,
  lundi_heuredpm         varchar(5)       DEFAULT NULL,
  lundi_heurefpm         varchar(5)       DEFAULT NULL,
  mardi_heuredam         varchar(5)       DEFAULT NULL,
  mardi_heurefam         varchar(5)       DEFAULT NULL,
  mardi_heuredpm         varchar(5)       DEFAULT NULL,
  mardi_heurefpm         varchar(5)       DEFAULT NULL,
  mercredi_heuredam      varchar(5)       DEFAULT NULL,
  mercredi_heurefam      varchar(5)       DEFAULT NULL,
  mercredi_heuredpm      varchar(5)       DEFAULT NULL,
  mercredi_heurefpm      varchar(5)       DEFAULT NULL,
  jeudi_heuredam         varchar(5)       DEFAULT NULL,
  jeudi_heurefam         varchar(5)       DEFAULT NULL,
  jeudi_heuredpm         varchar(5)       DEFAULT NULL,
  jeudi_heurefpm         varchar(5)       DEFAULT NULL,
  vendredi_heuredam      varchar(5)       DEFAULT NULL,
  vendredi_heurefam      varchar(5)       DEFAULT NULL,
  vendredi_heuredpm      varchar(5)       DEFAULT NULL,
  vendredi_heurefpm      varchar(5)       DEFAULT NULL,
  samedi_heuredam        varchar(5)       DEFAULT NULL,
  samedi_heurefam        varchar(5)       DEFAULT NULL,
  samedi_heuredpm        varchar(5)       DEFAULT NULL,
  samedi_heurefpm        varchar(5)       DEFAULT NULL,
  dimanche_heuredam      varchar(5)       DEFAULT NULL,
  dimanche_heurefam      varchar(5)       DEFAULT NULL,
  dimanche_heuredpm      varchar(5)       DEFAULT NULL,
  dimanche_heurefpm      varchar(5)       DEFAULT NULL
) ENGINE=innodb;
