CREATE TABLE llx_workshop_vehicule (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  date_creation datetime DEFAULT NULL,
  tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  vin varchar(50) NOT NULL DEFAULT '',
  entity integer NOT NULL DEFAULT 0,
  status integer NOT NULL DEFAULT 0,
  fk_vehicule_type integer NOT NULL DEFAULT 0,
  fk_vehicule_mark integer NOT NULL DEFAULT 0,
  modele varchar(255) DEFAULT NULL,
  immatriculation varchar(255) NOT NULL DEFAULT '',
  date_immat datetime DEFAULT NULL,
  fk_soc integer DEFAULT 0,
  km double DEFAULT 0,
  km_date datetime DEFAULT NULL,
  fk_contract_type integer DEFAULT NULL,
  date_end_contract datetime DEFAULT NULL,
  carrosserie longtext DEFAULT NULL,
  dim_pneu varchar(255) DEFAULT NULL,
  nb_pneu integer DEFAULT 0,
  import_key varchar(255) DEFAULT NULL,
  note_private longtext DEFAULT NULL,
  note_public longtext DEFAULT NULL,
  fk_user_create INTEGER DEFAULT NULL,
  fk_user_modif INTEGER DEFAULT NULL
)ENGINE=innodb;
