CREATE TABLE llx_workshopdet
(
    rowid                    integer AUTO_INCREMENT PRIMARY KEY,
    date_creation            datetime         DEFAULT NULL,
    tms                      timestamp        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    fk_operation_order       integer NOT NULL DEFAULT 0,
    fk_product               integer NOT NULL DEFAULT 0,
    fk_parent_line           integer          DEFAULT 0,
    label                    varchar(255)     DEFAULT NULL,
    description              longtext         DEFAULT NULL,
    qty                      double           DEFAULT 0,
    emplacement              varchar(255)     DEFAULT NULL,
    pc                       varchar(255)     DEFAULT NULL,
    time_planned             integer          DEFAULT 0,
    time_spent               integer          DEFAULT 0,
    product_type             integer NOT NULL DEFAULT 0,
    rang                     integer          DEFAULT 0,
    fk_user_creat            integer NOT NULL DEFAULT 0,
    fk_user_modif            integer          DEFAULT 0,
    import_key               varchar(14)      DEFAULT NULL,
    info_bits                integer          DEFAULT 0,
    price                    double           DEFAULT 0,
    fk_warehouse             varchar(255)     DEFAULT NULL,
    pr                       double           DEFAULT 0,
    fk_workshop_c_type integer,
    total_ht_reimbursement   double  NOT NULL DEFAULT 0,
    total_ht_part            double  NOT NULL DEFAULT 0,
    total_ht_service            double  NOT NULL DEFAULT 0,
    total_ht_external        double  NOT NULL DEFAULT 0,
    total_ht_mo              double  NOT NULL DEFAULT 0,
    total_ht                 double  NOT NULL DEFAULT 0,
    remise_percent           real             DEFAULT 0, -- % de la remise ligne (exemple 20%)
    remise                   real             DEFAULT 0  -- Montant calcule de la remise % sur PU HT (exemple 20)
) ENGINE = innodb;
