CREATE TABLE llx_workshop_operationorderdet (
  rowid                    integer AUTO_INCREMENT PRIMARY KEY,
  date_creation            datetime         DEFAULT NULL,
  tms                      timestamp        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_operationorder_jobs   integer NOT NULL DEFAULT 0,
  fk_product               integer          DEFAULT NULL,
  label                    varchar(255)     DEFAULT NULL,
  description              longtext         DEFAULT NULL,
  qty                      double           DEFAULT 0,
  price                    double           DEFAULT 0,
  remise_percent           real             DEFAULT 0,
  remise                   real             DEFAULT 0,
  total_ht                 double  NOT NULL DEFAULT 0,
  product_type             integer NOT NULL DEFAULT 0,
  rang                     integer          DEFAULT 0,
  pc                       varchar(255)     DEFAULT NULL,
  pr                       double           DEFAULT 0,
  fk_warehouse             integer          DEFAULT NULL,
  info_bits                integer          DEFAULT 0,
  total_ht_part            double  NOT NULL DEFAULT 0,
  total_ht_service         double  NOT NULL DEFAULT 0,
  total_ht_refund          double  NOT NULL DEFAULT 0,
  fk_user_creat            integer NOT NULL DEFAULT 0,
  fk_user_modif            integer          DEFAULT NULL,
  import_key               varchar(14)      DEFAULT NULL
) ENGINE=innodb;
